mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.AistView.as_view(), name='top'),
    path('<int:pk>/', views.DetailView.as_view(), name='datail_view'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('search/', views.ListView.as_view(), name='search'),
    path('test_login/', views.TestCreate.as_view(), name='test_login'),

]

mysite/register/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager


SKILLS = (
    ('1', 'Webデザイナー'),
    ('2', 'PG(フロントサイド)'),
    ('3', 'PG(サーバーサイド)'),
    ('4', 'デザイナー'),
    ('5', 'フォトグラファー'),
    ('6', 'イラストレーター'),
    ('7', 'ライター'),
    ('8', 'ブロガー'),
)

AREAS = (
    ('1', 'オンライン'),
    ('2', '北海道'),
    ('3', '青森県'),
    ('4', '岩手県'),
    ('5', '宮城県'),
    ('6', '秋田県'),
    ('7', '山形県'),
    ('8', '福島県'),
    ('9', '茨城県'),
    ('10', '栃木県'),
    ('11', '群馬県'),
    ('12', '埼玉県'),
    ('13', '千葉県'),
    ('14', '東京都'),
    ('15', '神奈川県'),
    ('16', '新潟県'),
    ('17', '富山県'),
    ('18', '石川県'),
    ('19', '福井県'),
    ('20', '山梨県'),
    ('21', '長野県'),
    ('22', '岐阜県'),
    ('23', '静岡県'),
    ('24', '愛知県'),
    ('25', '三重県'),
    ('26', '滋賀県'),
    ('27', '京都府'),
    ('28', '大阪府'),
    ('29', '兵庫県'),
    ('30', '奈良県'),
    ('31', '和歌山県'),
    ('32', '鳥取県'),
    ('33', '島根県'),
    ('34', '岡山県'),
    ('35', '広島県'),
    ('36', '山口県'),
    ('37', '徳島県'),
    ('38', '香川県'),
    ('39', '愛媛県'),
    ('40', '高知県'),
    ('41', '福岡県'),
    ('42', '佐賀県'),
    ('43', '長崎県'),
    ('44', '熊本県'),
    ('45', '大分県'),
    ('46', '宮崎県'),
    ('47', '鹿児島県'),
    ('48', '沖縄県'),
)

REQUESTS = (
    ('1', '応相談'),
    ('2', '無料'),
    ('3', '〜10,000円'),
    ('4', '10,000円〜'),
    ('5', '50,000円〜'),
    ('6', '100,000円〜'),
    ('7', '500,000円〜'),

)

class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    nick_name = models.CharField(_('ニックネーム'), max_length=30, blank=False)
    image = models.ImageField(('トップ画像'), upload_to='media/', blank=True)  # 画像はあとで解決する
    twitter = models.URLField(('Twitterアカウント'), blank=True)
    instagram = models.URLField(('Instagramアカウント'), max_length=150, blank=True)
    skill = models.CharField(('スキル'), max_length=150, choices=SKILLS, blank=True)
    area = models.CharField(('活動範囲'), max_length=150, choices=AREAS, blank=False)
    request_fee = models.CharField(('依頼料'), max_length=20, choices=REQUESTS, blank=False)
    portfolio = models.CharField(('ポートフォリオ'), max_length=150, blank=True)
    self_introduction = models.CharField(_('自己PR'), max_length=500, blank=True)
    created_at = models.DateTimeField(default=timezone.now)


    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email

mysite/register/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm
)
from django.contrib.auth import get_user_model

User = get_user_model()


class SearchForm(forms.Form):
    title = forms.CharField(
        initial='',
        label='タイトル',
        required = False, # 必須ではない
    )
    text = forms.CharField(
        initial='',
        label='内容',
        required=False,  # 必須ではない
    )

class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""
    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email


class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""

    top_image = forms.ImageField(widget=forms.FileInput)
    class Meta:
        model = User
        fields = ('nick_name','top_image','twitter','instagram',
                  'skill','area','request_fee','portfolio','self_introduction')#画像はあとで解決する
        widgets = {
            'self_introduction': forms.Textarea(attrs={'cols': 40, 'rows': 10}),
            'portfolio': forms.Textarea(attrs={'cols': 40, 'rows': 10})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

mysite/register/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, resolve_url
from django.template.loader import render_to_string
from django.views import generic
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm
)
from django.urls import reverse_lazy

from django.db.models import Q

User = get_user_model()

class AistView(generic.ListView):
    model = User
    template_name = 'register/top.html'
    paginate_by = 8
    queryset = User.objects.order_by('-created_at')

    def get_queryset(self):
        result = super(AistView, self).get_queryset()
        query = self.request.GET.get('q')

        if query:
            result = User.objects.filter(Q(skill__icontains=query))

        return result

class ListView(generic.ListView):
    model = User
    template_name = 'register/top.html'
    paginate_by = 8

    def get_queryset(self):
        result = super(ListView, self).get_queryset()
        query = self.request.GET.get('q')

        if query:
            result = User.objects.filter(Q(nick_name__icontains=query) | Q(self_introduction__icontains=query))

        return result


class DetailView(generic.DetailView):
    model = User
    template_name = 'register/top.html'


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'register/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    model = User
    template_name = 'register/top.html'


class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'register/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string('register/mail_template/create/subject.txt', context)
        message = render_to_string('register/mail_template/create/message.txt', context)

        user.email_user(subject, message)
        return redirect('register:user_create_done')





class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録したよ"""
    template_name = 'register/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'register/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    model = User
    template_name = 'register/user_detail.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'register/user_form.html'
    success_url = reverse_lazy('app:file_list')

    def get_success_url(self):
        return resolve_url('register:user_detail', pk=self.kwargs['pk'])

class TestCreate(generic.CreateView):
    template_name = 'register/user_form.html'
    form_class = UserUpdateForm

    def form_valid(self,form):

        user = form.save(commit=False)
        user.is_active = True
        user.save()

        return redirect('register:user_detail', pk=user.pk)

mysite/register/templates/register/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Freelanze - {% block title %}{% endblock %}</title>
</head>
<body>
<!-- 本番ー -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'register:top' %}">freelanze</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li>
            <a class="nav-item nav-link" href="{% url 'register:user_detail' user.pk %}">登録情報の確認</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:user_update' user.pk %}">マイページ</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'register:login' %}">
            ようこそ、ゲストさん！ログインはこちら
          </a>
          </li>
          {% endif %}
        </ul>
          <div class="btn-group">
              <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  スキルで絞り込む
              </button>
              <form class="form-inline my-2 my-lg-0" action="" method="get" accept-charset="utf-8">
                  <div class="dropdown-menu">
                      <button class="dropdown-item" type="submit" value="1" name="q">Webデザイナー</button>
                      <button class="dropdown-item" type="submit" value="2" name="q">PG(フロントサイド)</button>
                      <button class="dropdown-item" type="submit" value="3" name="q">PG（サーバーサイド）</button>
                      <button class="dropdown-item" type="submit" value="4" name="q">デザイナー</button>
                      <button class="dropdown-item" type="submit" value="5" name="q">フォトグラファー</button>
                      <button class="dropdown-item" type="submit" value="6" name="q">イラストレーター</button>
                      <button class="dropdown-item" type="submit" value="7" name="q">ライター</button>
                      <button class="dropdown-item" type="submit" value="8" name="q">ブロガー</button>
                  </div><!-- /.dropdown-menu -->
              </form>
          </div><!-- /.btn-group -->
          <form class="form-inline my-2 my-lg-0" action="/search" method="get" accept-charset="utf-8">
              <input type="search" class="form-control mr-sm-2" placeholder="キーワードで検索" name="q" aria-label="検索...">
              <button type="submit" class="btn btn-outline-info my-2 my-sm-0">検索</button>
          </form>
      </div>
    </nav>

<!-- top画像ー -->
<img class="img-fluid" src="/media/freelanze-top-image.png" style="margin-top: 55px">
<main>
    <!-- メインコンテンツ -->
    <div class="container mt-auto">
        {% block content %}{% endblock %}
    </div>
</main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

mysite/register/templates/register/mypage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>うんこ作るくん</h1>
</body>
</html>

mysite/register/templates/register/top.html
{% extends "register/base.html" %}
{% block title %}Topページ{% endblock %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-12" style="mx-auto">
            <p class="text-center"><span class="bg-white text-primary">＼新着フリーランス一覧／</span></p>
        </div>
        {% for product in user_list %}
        <div class="col-6 col-md-6">
            <div class="datail" data-toggle="modal" data-target="#{{ product.id }}">
            <div class="card mb-3" style="max-width: 500px;">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <div class="img-thumbnail">
                        <img src="{{ product.top_image.url }}" class="aaa" width="100%" heught="100%">
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text">職種：{{ product.get_skill_display }}</p>
                            <p class="card-text">依頼料：{{ product.get_request_fee_display }}</p>
                            <p class="card-text">名前：{{ product.nick_name }}</p>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>

        <!-- モーダルの設定 -->
        <div class="modal fade" id="{{ product.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">「{{ product.nick_name }}」の詳細情報</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="container">
                            <div class="row">
                                <div class="col">
                                    <div class="text-center">
                                        <img src="{{ product.top_image.url }}" class="rounded-circle" alt="参考画像" style="width:auto; height:200px" >
                                    </div>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-6">
                                    <div class="text-center">
                                        <span class="border-bottom">

                                        {% if product.twitter %}
                                        <a href="{{ product.twitter }}">
                                            <i class="fab fa-twitter fa-3x my-example fa-fw"></i>
                                            ←check
                                        </a>
                                        {% endif %}
                                            </span>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="text-center">
                                        <span class="border-bottom">
                                        {% if product.instagram %}
                                        <a href="{{ product.instagram }}" class="insta_btn">
                                            <span class="insta">
                                                <i class="fab fa-instagram"></i>
                                            </span>←check</a>
                                        {% endif %}
                                        </span>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <p class='border-bottom'>■ニックネーム<br>{{ product.nick_name }}</p>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col">
                                    <p class='border-bottom'>■職種<br>{{ product.get_skill_display }}</br></p>
                                    <p class='border-bottom'>■活動地域<br>{{ product.get_area_display }}</br></p>
                                    <p class='border-bottom'>■依頼料<br>{{ product.get_request_fee_display }}</br></p>
                                    {% if product.portfolio %}
                                    <p>■ポートフォリオ一覧<br>{{ product.portfolio | linebreaksbr }}</br></p>
                                    {% endif %}
                                    <p>■自己PR<br>{{ product.self_introduction | linebreaksbr }}</br></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a href="mailto:{{ product.email }}">
                            <button type="submit" class="btn btn-outline-info my-2 my-sm-0">直接メールでお仕事の依頼をする</button>
                        </a>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                    </div><!-- /.modal-footer -->
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        {% endfor %}
    </div>
</div>
<!--ページネーション↓-->
<ul class="pagination">
    <!-- 前へ の部分 -->
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
    {% endif %}
    <!-- 数字の部分 -->
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}
    <!-- 次へ の部分 -->
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    {% endif %}
</ul>



<!--ページネーション↑-->
<div class="container-fluid">
    <div class="row">
        <div class="col-12"><p class="text-center"><span class="bg-white text-primary">＼おすすめフリーランスTop5／</span></p></div>
        <div class="col-12 col-md-6">
            <div class="card mb-3" style="max-width: 500px;">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="..." class="card-img" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">カードのタイトル</h5>
                            <p class="card-text">...</p>
                            <p class="card-text"><small class="text-muted">最終更新3分前</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- モーダルの設定 -->
        <div class="modal fade" id="{{ product.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">「{{ product.nick_name }}」の詳細情報</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-6">
                                  <img src="{{ product.top_image.url }}" class="img-thumbnail">
                                </div>
                                <div class="col-6">
                                    <div class="col">
                                        {% if product.twitter %}
                                        <a href="{{ product.twitter }}"><i class="fab fa-twitter fa-3x my-example fa-fw"></i></a>
                                        {% endif %}
                                    </div>
                                    <div class="col">
                                        {% if product.instagram %}
                                        <a href="{{ product.instagram }}"><i class="fab fa-instagram fa-3x my-example fa-fw"></i></a>
                                        {% endif %}
                                    </div>
                                    <div class="col">
                                        <div class="d-flex align-items-end">
                                        <p class='border-bottom'>■ニックネーム<br>{{ product.nick_name }}</br></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <p class='border-bottom'>■職種<br>{{ product.get_skill_display }}</br></p>
                                    <p class='border-bottom'>■活動地域<br>{{ product.get_area_display }}</br></p>
                                    <p class='border-bottom'>■依頼料<br>{{ product.get_request_fee_display }}</br></p>
                                    <p>■ポートフォリオ一覧<br>{{ product.portfolio | linebreaksbr }}</br></p>
                                    <p>■自己PR<br>{{ product.self_introduction | linebreaksbr }}</br></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a href="mailto:{{ product.email }}">
                            <button type="submit" class="btn btn-outline-info my-2 my-sm-0">直接メールでお仕事の依頼をする</button>
                        </a>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                    </div><!-- /.modal-footer -->
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
</div>

{% endblock %}

mysite/register/templates/register/user_create.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

mysite/register/templates/register/user_create_complte.html
{% extends "register/base.html" %}
{% block content %}
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}